# Generated by Django 4.0.3 on 2022-04-08 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_userfriends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='second_name',
        ),
    ]
