# Generated by Django 4.0.3 on 2022-04-08 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_friendrequest_delete_userfriend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='main.profile')),
                ('users', models.ManyToManyField(to='main.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
